{
    "cells": [
     {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {},
      "outputs": [
       {
        "name": "stdout",
        "output_type": "stream",
        "text": [
         "Requirement already satisfied: google-cloud-aiplatform in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (1.70.0)\n",
         "Requirement already satisfied: langchain in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (0.3.3)\n",
         "Requirement already satisfied: langchain_core in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (0.3.10)\n",
         "Requirement already satisfied: langchain_community in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (0.3.2)\n",
         "Requirement already satisfied: langchain-google-vertexai in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (2.0.5)\n",
         "Collecting cloudpickle==3.0.0\n",
         "  Using cached cloudpickle-3.0.0-py3-none-any.whl.metadata (7.0 kB)\n",
         "Collecting pydantic==2.7.4\n",
         "  Using cached pydantic-2.7.4-py3-none-any.whl.metadata (109 kB)\n",
         "Collecting langchain_google_community\n",
         "  Using cached langchain_google_community-2.0.1-py3-none-any.whl.metadata (3.4 kB)\n",
         "Collecting google-cloud-discoveryengine\n",
         "  Using cached google_cloud_discoveryengine-0.12.3-py3-none-any.whl.metadata (5.2 kB)\n",
         "Collecting google-api-python-client\n",
         "  Using cached google_api_python_client-2.149.0-py2.py3-none-any.whl.metadata (6.7 kB)\n",
         "Requirement already satisfied: google-auth in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (2.35.0)\n",
         "Requirement already satisfied: nest-asyncio in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (1.6.0)\n",
         "Collecting psycopg2\n",
         "  Using cached psycopg2-2.9.9.tar.gz (384 kB)\n",
         "  Installing build dependencies ... \u001b[?25ldone\n",
         "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25ldone\n",
         "\u001b[?25h  Preparing metadata (pyproject.toml) ... \u001b[?25ldone\n",
         "\u001b[?25hCollecting psycopg2-binary\n",
         "  Using cached psycopg2_binary-2.9.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)\n",
         "Requirement already satisfied: annotated-types>=0.4.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from pydantic==2.7.4) (0.7.0)\n",
         "Collecting pydantic-core==2.18.4 (from pydantic==2.7.4)\n",
         "  Using cached pydantic_core-2.18.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.5 kB)\n",
         "Requirement already satisfied: typing-extensions>=4.6.1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from pydantic==2.7.4) (4.12.2)\n",
         "Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-cloud-aiplatform) (2.21.0)\n",
         "Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform) (1.24.0)\n",
         "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform) (4.25.5)\n",
         "Requirement already satisfied: packaging>=14.3 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform) (24.1)\n",
         "Requirement already satisfied: google-cloud-storage<3.0.0dev,>=1.32.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform) (2.18.2)\n",
         "Requirement already satisfied: google-cloud-bigquery!=3.20.0,<4.0.0dev,>=1.15.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform) (3.26.0)\n",
         "Requirement already satisfied: google-cloud-resource-manager<3.0.0dev,>=1.3.3 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform) (1.12.5)\n",
         "Requirement already satisfied: shapely<3.0.0dev in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform) (2.0.6)\n",
         "Requirement already satisfied: docstring-parser<1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform) (0.16)\n",
         "Requirement already satisfied: PyYAML>=5.3 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain) (6.0.2)\n",
         "Requirement already satisfied: SQLAlchemy<3,>=1.4 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain) (2.0.35)\n",
         "Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain) (3.10.10)\n",
         "Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain) (4.0.3)\n",
         "Requirement already satisfied: langchain-text-splitters<0.4.0,>=0.3.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain) (0.3.0)\n",
         "Requirement already satisfied: langsmith<0.2.0,>=0.1.17 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain) (0.1.134)\n",
         "Requirement already satisfied: numpy<2,>=1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain) (1.26.4)\n",
         "Requirement already satisfied: requests<3,>=2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain) (2.32.3)\n",
         "Requirement already satisfied: tenacity!=8.4.0,<9.0.0,>=8.1.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain) (8.3.0)\n",
         "Requirement already satisfied: jsonpatch<2.0,>=1.33 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain_core) (1.33)\n",
         "Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain_community) (0.6.7)\n",
         "Requirement already satisfied: pydantic-settings<3.0.0,>=2.4.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain_community) (2.5.2)\n",
         "Requirement already satisfied: httpx<0.28.0,>=0.27.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain-google-vertexai) (0.27.2)\n",
         "Requirement already satisfied: httpx-sse<0.5.0,>=0.4.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain-google-vertexai) (0.4.0)\n",
         "Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain_google_community) (2.4.1)\n",
         "Requirement already satisfied: grpcio<2.0.0,>=1.62.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain_google_community) (1.66.2)\n",
         "Collecting httplib2<1.dev0,>=0.19.0 (from google-api-python-client)\n",
         "  Using cached httplib2-0.22.0-py3-none-any.whl.metadata (2.6 kB)\n",
         "Collecting google-auth-httplib2<1.0.0,>=0.2.0 (from google-api-python-client)\n",
         "  Using cached google_auth_httplib2-0.2.0-py2.py3-none-any.whl.metadata (2.2 kB)\n",
         "Collecting uritemplate<5,>=3.0.1 (from google-api-python-client)\n",
         "  Using cached uritemplate-4.1.1-py2.py3-none-any.whl.metadata (2.9 kB)\n",
         "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-auth) (5.5.0)\n",
         "Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-auth) (0.4.1)\n",
         "Requirement already satisfied: rsa<5,>=3.1.4 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-auth) (4.9)\n",
         "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (2.4.3)\n",
         "Requirement already satisfied: aiosignal>=1.1.2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.3.1)\n",
         "Requirement already satisfied: attrs>=17.3.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (24.2.0)\n",
         "Requirement already satisfied: frozenlist>=1.1.1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.4.1)\n",
         "Requirement already satisfied: multidict<7.0,>=4.5 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (6.1.0)\n",
         "Requirement already satisfied: yarl<2.0,>=1.12.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.15.1)\n",
         "Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain_community) (3.22.0)\n",
         "Requirement already satisfied: typing-inspect<1,>=0.4.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from dataclasses-json<0.7,>=0.5.7->langchain_community) (0.9.0)\n",
         "Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-cloud-aiplatform) (1.65.0)\n",
         "Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-cloud-aiplatform) (1.62.3)\n",
         "Requirement already satisfied: google-resumable-media<3.0dev,>=2.0.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0dev,>=1.15.0->google-cloud-aiplatform) (2.7.2)\n",
         "Requirement already satisfied: python-dateutil<3.0dev,>=2.7.3 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0dev,>=1.15.0->google-cloud-aiplatform) (2.9.0.post0)\n",
         "Requirement already satisfied: grpc-google-iam-v1<1.0.0dev,>=0.12.4 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-resource-manager<3.0.0dev,>=1.3.3->google-cloud-aiplatform) (0.13.1)\n",
         "Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-storage<3.0.0dev,>=1.32.0->google-cloud-aiplatform) (1.6.0)\n",
         "Collecting pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 (from httplib2<1.dev0,>=0.19.0->google-api-python-client)\n",
         "  Using cached pyparsing-3.1.4-py3-none-any.whl.metadata (5.1 kB)\n",
         "Requirement already satisfied: anyio in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from httpx<0.28.0,>=0.27.0->langchain-google-vertexai) (4.6.0)\n",
         "Requirement already satisfied: certifi in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from httpx<0.28.0,>=0.27.0->langchain-google-vertexai) (2024.8.30)\n",
         "Requirement already satisfied: httpcore==1.* in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from httpx<0.28.0,>=0.27.0->langchain-google-vertexai) (1.0.6)\n",
         "Requirement already satisfied: idna in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from httpx<0.28.0,>=0.27.0->langchain-google-vertexai) (3.10)\n",
         "Requirement already satisfied: sniffio in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from httpx<0.28.0,>=0.27.0->langchain-google-vertexai) (1.3.1)\n",
         "Requirement already satisfied: h11<0.15,>=0.13 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from httpcore==1.*->httpx<0.28.0,>=0.27.0->langchain-google-vertexai) (0.14.0)\n",
         "Requirement already satisfied: jsonpointer>=1.9 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from jsonpatch<2.0,>=1.33->langchain_core) (3.0.0)\n",
         "Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langsmith<0.2.0,>=0.1.17->langchain) (3.10.6)\n",
         "Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langsmith<0.2.0,>=0.1.17->langchain) (1.0.0)\n",
         "Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth) (0.6.1)\n",
         "Requirement already satisfied: python-dotenv>=0.21.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from pydantic-settings<3.0.0,>=2.4.0->langchain_community) (1.0.1)\n",
         "Requirement already satisfied: charset-normalizer<4,>=2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from requests<3,>=2->langchain) (3.4.0)\n",
         "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from requests<3,>=2->langchain) (2.2.3)\n",
         "Requirement already satisfied: greenlet!=0.4.17 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from SQLAlchemy<3,>=1.4->langchain) (3.1.1)\n",
         "Requirement already satisfied: six>=1.5 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from python-dateutil<3.0dev,>=2.7.3->google-cloud-bigquery!=3.20.0,<4.0.0dev,>=1.15.0->google-cloud-aiplatform) (1.16.0)\n",
         "Requirement already satisfied: mypy-extensions>=0.3.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain_community) (1.0.0)\n",
         "Requirement already satisfied: propcache>=0.2.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from yarl<2.0,>=1.12.0->aiohttp<4.0.0,>=3.8.3->langchain) (0.2.0)\n",
         "Requirement already satisfied: exceptiongroup>=1.0.2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from anyio->httpx<0.28.0,>=0.27.0->langchain-google-vertexai) (1.2.2)\n",
         "Using cached cloudpickle-3.0.0-py3-none-any.whl (20 kB)\n",
         "Using cached pydantic-2.7.4-py3-none-any.whl (409 kB)\n",
         "Using cached pydantic_core-2.18.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)\n",
         "Using cached langchain_google_community-2.0.1-py3-none-any.whl (77 kB)\n",
         "Using cached google_cloud_discoveryengine-0.12.3-py3-none-any.whl (2.5 MB)\n",
         "Using cached google_api_python_client-2.149.0-py2.py3-none-any.whl (12.3 MB)\n",
         "Using cached psycopg2_binary-2.9.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)\n",
         "Using cached google_auth_httplib2-0.2.0-py2.py3-none-any.whl (9.3 kB)\n",
         "Using cached httplib2-0.22.0-py3-none-any.whl (96 kB)\n",
         "Using cached uritemplate-4.1.1-py2.py3-none-any.whl (10 kB)\n",
         "Using cached pyparsing-3.1.4-py3-none-any.whl (104 kB)\n",
         "Building wheels for collected packages: psycopg2\n",
         "  Building wheel for psycopg2 (pyproject.toml) ... \u001b[?25lerror\n",
         "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
         "  \n",
         "  \u001b[31m×\u001b[0m \u001b[32mBuilding wheel for psycopg2 \u001b[0m\u001b[1;32m(\u001b[0m\u001b[32mpyproject.toml\u001b[0m\u001b[1;32m)\u001b[0m did not run successfully.\n",
         "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
         "  \u001b[31m╰─>\u001b[0m \u001b[31m[35 lines of output]\u001b[0m\n",
         "  \u001b[31m   \u001b[0m running bdist_wheel\n",
         "  \u001b[31m   \u001b[0m running build\n",
         "  \u001b[31m   \u001b[0m running build_py\n",
         "  \u001b[31m   \u001b[0m creating build/lib.linux-x86_64-cpython-310/psycopg2\n",
         "  \u001b[31m   \u001b[0m copying lib/pool.py -> build/lib.linux-x86_64-cpython-310/psycopg2\n",
         "  \u001b[31m   \u001b[0m copying lib/_json.py -> build/lib.linux-x86_64-cpython-310/psycopg2\n",
         "  \u001b[31m   \u001b[0m copying lib/__init__.py -> build/lib.linux-x86_64-cpython-310/psycopg2\n",
         "  \u001b[31m   \u001b[0m copying lib/errors.py -> build/lib.linux-x86_64-cpython-310/psycopg2\n",
         "  \u001b[31m   \u001b[0m copying lib/errorcodes.py -> build/lib.linux-x86_64-cpython-310/psycopg2\n",
         "  \u001b[31m   \u001b[0m copying lib/extensions.py -> build/lib.linux-x86_64-cpython-310/psycopg2\n",
         "  \u001b[31m   \u001b[0m copying lib/_range.py -> build/lib.linux-x86_64-cpython-310/psycopg2\n",
         "  \u001b[31m   \u001b[0m copying lib/_ipaddress.py -> build/lib.linux-x86_64-cpython-310/psycopg2\n",
         "  \u001b[31m   \u001b[0m copying lib/tz.py -> build/lib.linux-x86_64-cpython-310/psycopg2\n",
         "  \u001b[31m   \u001b[0m copying lib/sql.py -> build/lib.linux-x86_64-cpython-310/psycopg2\n",
         "  \u001b[31m   \u001b[0m copying lib/extras.py -> build/lib.linux-x86_64-cpython-310/psycopg2\n",
         "  \u001b[31m   \u001b[0m running build_ext\n",
         "  \u001b[31m   \u001b[0m building 'psycopg2._psycopg' extension\n",
         "  \u001b[31m   \u001b[0m creating build/temp.linux-x86_64-cpython-310/psycopg\n",
         "  \u001b[31m   \u001b[0m x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC \"-DPSYCOPG_VERSION=2.9.9 (dt dec pq3 ext lo64)\" -DPSYCOPG_DEBUG=1 -DPG_VERSION_NUM=140012 -DHAVE_LO64=1 -DPSYCOPG_DEBUG=1 -I/home/imrenagi/projects/generative-ai/.venv/include -I/usr/include/python3.10 -I. -I/usr/include/postgresql -I/usr/include/postgresql/14/server -I/usr/include/libxml2 -c psycopg/adapter_asis.c -o build/temp.linux-x86_64-cpython-310/psycopg/adapter_asis.o -Wdeclaration-after-statement\n",
         "  \u001b[31m   \u001b[0m In file included from psycopg/adapter_asis.c:28:\n",
         "  \u001b[31m   \u001b[0m ./psycopg/psycopg.h:36:10: fatal error: libpq-fe.h: No such file or directory\n",
         "  \u001b[31m   \u001b[0m    36 | #include <libpq-fe.h>\n",
         "  \u001b[31m   \u001b[0m       |          ^~~~~~~~~~~~\n",
         "  \u001b[31m   \u001b[0m compilation terminated.\n",
         "  \u001b[31m   \u001b[0m \n",
         "  \u001b[31m   \u001b[0m It appears you are missing some prerequisite to build the package from source.\n",
         "  \u001b[31m   \u001b[0m \n",
         "  \u001b[31m   \u001b[0m You may install a binary package by installing 'psycopg2-binary' from PyPI.\n",
         "  \u001b[31m   \u001b[0m If you want to install psycopg2 from source, please install the packages\n",
         "  \u001b[31m   \u001b[0m required for the build and try again.\n",
         "  \u001b[31m   \u001b[0m \n",
         "  \u001b[31m   \u001b[0m For further information please check the 'doc/src/install.rst' file (also at\n",
         "  \u001b[31m   \u001b[0m <https://www.psycopg.org/docs/install.html>).\n",
         "  \u001b[31m   \u001b[0m \n",
         "  \u001b[31m   \u001b[0m error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1\n",
         "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
         "  \n",
         "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
         "\u001b[?25h\u001b[31m  ERROR: Failed building wheel for psycopg2\u001b[0m\u001b[31m\n",
         "\u001b[0mFailed to build psycopg2\n",
         "\u001b[31mERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (psycopg2)\u001b[0m\u001b[31m\n",
         "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n",
         "Requirement already satisfied: asyncio==3.4.3 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (3.4.3)\n",
         "Requirement already satisfied: asyncpg==0.27.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (0.27.0)\n",
         "Requirement already satisfied: cloud-sql-python-connector==1.2.3 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from cloud-sql-python-connector[asyncpg]==1.2.3) (1.2.3)\n",
         "Requirement already satisfied: numpy in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (1.26.4)\n",
         "Requirement already satisfied: pandas in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (2.2.3)\n",
         "Requirement already satisfied: pgvector in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (0.3.5)\n",
         "Requirement already satisfied: aiohttp in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (3.10.10)\n",
         "Requirement already satisfied: cryptography>=38.0.3 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (43.0.1)\n",
         "Requirement already satisfied: Requests in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (2.32.3)\n",
         "Requirement already satisfied: google-auth in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (2.35.0)\n",
         "Requirement already satisfied: python-dateutil>=2.8.2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from pandas) (2.9.0.post0)\n",
         "Requirement already satisfied: pytz>=2020.1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from pandas) (2024.2)\n",
         "Requirement already satisfied: tzdata>=2022.7 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from pandas) (2024.2)\n",
         "Requirement already satisfied: cffi>=1.12 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from cryptography>=38.0.3->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (1.17.1)\n",
         "Requirement already satisfied: six>=1.5 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n",
         "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (2.4.3)\n",
         "Requirement already satisfied: aiosignal>=1.1.2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (1.3.1)\n",
         "Requirement already satisfied: attrs>=17.3.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (24.2.0)\n",
         "Requirement already satisfied: frozenlist>=1.1.1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (1.4.1)\n",
         "Requirement already satisfied: multidict<7.0,>=4.5 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (6.1.0)\n",
         "Requirement already satisfied: yarl<2.0,>=1.12.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (1.15.1)\n",
         "Requirement already satisfied: async-timeout<5.0,>=4.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (4.0.3)\n",
         "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-auth->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (5.5.0)\n",
         "Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-auth->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (0.4.1)\n",
         "Requirement already satisfied: rsa<5,>=3.1.4 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-auth->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (4.9)\n",
         "Requirement already satisfied: charset-normalizer<4,>=2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from Requests->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (3.4.0)\n",
         "Requirement already satisfied: idna<4,>=2.5 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from Requests->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (3.10)\n",
         "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from Requests->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (2.2.3)\n",
         "Requirement already satisfied: certifi>=2017.4.17 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from Requests->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (2024.8.30)\n",
         "Requirement already satisfied: pycparser in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from cffi>=1.12->cryptography>=38.0.3->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (2.22)\n",
         "Requirement already satisfied: typing-extensions>=4.1.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from multidict<7.0,>=4.5->aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (4.12.2)\n",
         "Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (0.6.1)\n",
         "Requirement already satisfied: propcache>=0.2.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from yarl<2.0,>=1.12.0->aiohttp->cloud-sql-python-connector==1.2.3->cloud-sql-python-connector[asyncpg]==1.2.3) (0.2.0)\n",
         "Note: you may need to restart the kernel to use updated packages.\n",
         "Requirement already satisfied: google-cloud-aiplatform[langchain,reasoningengine] in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (1.70.0)\n",
         "Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-cloud-aiplatform[langchain,reasoningengine]) (2.21.0)\n",
         "Requirement already satisfied: google-auth<3.0.0dev,>=2.14.1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform[langchain,reasoningengine]) (2.35.0)\n",
         "Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform[langchain,reasoningengine]) (1.24.0)\n",
         "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform[langchain,reasoningengine]) (4.25.5)\n",
         "Requirement already satisfied: packaging>=14.3 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform[langchain,reasoningengine]) (24.1)\n",
         "Requirement already satisfied: google-cloud-storage<3.0.0dev,>=1.32.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform[langchain,reasoningengine]) (2.18.2)\n",
         "Requirement already satisfied: google-cloud-bigquery!=3.20.0,<4.0.0dev,>=1.15.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform[langchain,reasoningengine]) (3.26.0)\n",
         "Requirement already satisfied: google-cloud-resource-manager<3.0.0dev,>=1.3.3 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform[langchain,reasoningengine]) (1.12.5)\n",
         "Requirement already satisfied: shapely<3.0.0dev in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform[langchain,reasoningengine]) (2.0.6)\n",
         "Requirement already satisfied: pydantic<3 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform[langchain,reasoningengine]) (2.9.2)\n",
         "Requirement already satisfied: docstring-parser<1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform[langchain,reasoningengine]) (0.16)\n",
         "Collecting langchain<0.3,>=0.1.16 (from google-cloud-aiplatform[langchain,reasoningengine])\n",
         "  Using cached langchain-0.2.16-py3-none-any.whl.metadata (7.1 kB)\n",
         "Collecting langchain-core<0.3 (from google-cloud-aiplatform[langchain,reasoningengine])\n",
         "  Using cached langchain_core-0.2.41-py3-none-any.whl.metadata (6.2 kB)\n",
         "Collecting langchain-google-vertexai<2 (from google-cloud-aiplatform[langchain,reasoningengine])\n",
         "  Using cached langchain_google_vertexai-1.0.10-py3-none-any.whl.metadata (3.8 kB)\n",
         "Requirement already satisfied: openinference-instrumentation-langchain<0.2,>=0.1.19 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform[langchain,reasoningengine]) (0.1.28)\n",
         "Requirement already satisfied: tenacity<=8.3 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform[langchain,reasoningengine]) (8.3.0)\n",
         "Requirement already satisfied: orjson<=3.10.6 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform[langchain,reasoningengine]) (3.10.6)\n",
         "Requirement already satisfied: cloudpickle<4.0,>=3.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform[langchain,reasoningengine]) (3.1.0)\n",
         "Requirement already satisfied: google-cloud-trace<2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform[langchain,reasoningengine]) (1.13.5)\n",
         "Requirement already satisfied: opentelemetry-sdk<2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform[langchain,reasoningengine]) (1.27.0)\n",
         "Requirement already satisfied: opentelemetry-exporter-gcp-trace<2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-aiplatform[langchain,reasoningengine]) (1.7.0)\n",
         "Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-cloud-aiplatform[langchain,reasoningengine]) (1.65.0)\n",
         "Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-cloud-aiplatform[langchain,reasoningengine]) (2.32.3)\n",
         "Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-cloud-aiplatform[langchain,reasoningengine]) (1.66.2)\n",
         "Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-cloud-aiplatform[langchain,reasoningengine]) (1.62.3)\n",
         "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-auth<3.0.0dev,>=2.14.1->google-cloud-aiplatform[langchain,reasoningengine]) (5.5.0)\n",
         "Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-auth<3.0.0dev,>=2.14.1->google-cloud-aiplatform[langchain,reasoningengine]) (0.4.1)\n",
         "Requirement already satisfied: rsa<5,>=3.1.4 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-auth<3.0.0dev,>=2.14.1->google-cloud-aiplatform[langchain,reasoningengine]) (4.9)\n",
         "Requirement already satisfied: google-cloud-core<3.0.0dev,>=2.4.1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0dev,>=1.15.0->google-cloud-aiplatform[langchain,reasoningengine]) (2.4.1)\n",
         "Requirement already satisfied: google-resumable-media<3.0dev,>=2.0.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0dev,>=1.15.0->google-cloud-aiplatform[langchain,reasoningengine]) (2.7.2)\n",
         "Requirement already satisfied: python-dateutil<3.0dev,>=2.7.3 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-bigquery!=3.20.0,<4.0.0dev,>=1.15.0->google-cloud-aiplatform[langchain,reasoningengine]) (2.9.0.post0)\n",
         "Requirement already satisfied: grpc-google-iam-v1<1.0.0dev,>=0.12.4 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-resource-manager<3.0.0dev,>=1.3.3->google-cloud-aiplatform[langchain,reasoningengine]) (0.13.1)\n",
         "Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from google-cloud-storage<3.0.0dev,>=1.32.0->google-cloud-aiplatform[langchain,reasoningengine]) (1.6.0)\n",
         "Requirement already satisfied: PyYAML>=5.3 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain<0.3,>=0.1.16->google-cloud-aiplatform[langchain,reasoningengine]) (6.0.2)\n",
         "Requirement already satisfied: SQLAlchemy<3,>=1.4 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain<0.3,>=0.1.16->google-cloud-aiplatform[langchain,reasoningengine]) (2.0.35)\n",
         "Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain<0.3,>=0.1.16->google-cloud-aiplatform[langchain,reasoningengine]) (3.10.10)\n",
         "Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain<0.3,>=0.1.16->google-cloud-aiplatform[langchain,reasoningengine]) (4.0.3)\n",
         "Collecting langchain-text-splitters<0.3.0,>=0.2.0 (from langchain<0.3,>=0.1.16->google-cloud-aiplatform[langchain,reasoningengine])\n",
         "  Using cached langchain_text_splitters-0.2.4-py3-none-any.whl.metadata (2.3 kB)\n",
         "Requirement already satisfied: langsmith<0.2.0,>=0.1.17 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain<0.3,>=0.1.16->google-cloud-aiplatform[langchain,reasoningengine]) (0.1.134)\n",
         "Requirement already satisfied: numpy<2,>=1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain<0.3,>=0.1.16->google-cloud-aiplatform[langchain,reasoningengine]) (1.26.4)\n",
         "Requirement already satisfied: jsonpatch<2.0,>=1.33 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain-core<0.3->google-cloud-aiplatform[langchain,reasoningengine]) (1.33)\n",
         "Requirement already satisfied: typing-extensions>=4.7 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain-core<0.3->google-cloud-aiplatform[langchain,reasoningengine]) (4.12.2)\n",
         "Requirement already satisfied: httpx<0.28.0,>=0.27.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain-google-vertexai<2->google-cloud-aiplatform[langchain,reasoningengine]) (0.27.2)\n",
         "Requirement already satisfied: httpx-sse<0.5.0,>=0.4.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langchain-google-vertexai<2->google-cloud-aiplatform[langchain,reasoningengine]) (0.4.0)\n",
         "Requirement already satisfied: openinference-instrumentation>=0.1.17 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from openinference-instrumentation-langchain<0.2,>=0.1.19->google-cloud-aiplatform[langchain,reasoningengine]) (0.1.18)\n",
         "Requirement already satisfied: openinference-semantic-conventions>=0.1.9 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from openinference-instrumentation-langchain<0.2,>=0.1.19->google-cloud-aiplatform[langchain,reasoningengine]) (0.1.10)\n",
         "Requirement already satisfied: opentelemetry-api in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from openinference-instrumentation-langchain<0.2,>=0.1.19->google-cloud-aiplatform[langchain,reasoningengine]) (1.27.0)\n",
         "Requirement already satisfied: opentelemetry-instrumentation in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from openinference-instrumentation-langchain<0.2,>=0.1.19->google-cloud-aiplatform[langchain,reasoningengine]) (0.48b0)\n",
         "Requirement already satisfied: opentelemetry-semantic-conventions in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from openinference-instrumentation-langchain<0.2,>=0.1.19->google-cloud-aiplatform[langchain,reasoningengine]) (0.48b0)\n",
         "Requirement already satisfied: wrapt in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from openinference-instrumentation-langchain<0.2,>=0.1.19->google-cloud-aiplatform[langchain,reasoningengine]) (1.16.0)\n",
         "Requirement already satisfied: opentelemetry-resourcedetector-gcp==1.*,>=1.5.0dev0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from opentelemetry-exporter-gcp-trace<2->google-cloud-aiplatform[langchain,reasoningengine]) (1.7.0a0)\n",
         "Requirement already satisfied: deprecated>=1.2.6 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from opentelemetry-api->openinference-instrumentation-langchain<0.2,>=0.1.19->google-cloud-aiplatform[langchain,reasoningengine]) (1.2.14)\n",
         "Requirement already satisfied: importlib-metadata<=8.4.0,>=6.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from opentelemetry-api->openinference-instrumentation-langchain<0.2,>=0.1.19->google-cloud-aiplatform[langchain,reasoningengine]) (8.4.0)\n",
         "Requirement already satisfied: annotated-types>=0.6.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from pydantic<3->google-cloud-aiplatform[langchain,reasoningengine]) (0.7.0)\n",
         "Requirement already satisfied: pydantic-core==2.23.4 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from pydantic<3->google-cloud-aiplatform[langchain,reasoningengine]) (2.23.4)\n",
         "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain<0.3,>=0.1.16->google-cloud-aiplatform[langchain,reasoningengine]) (2.4.3)\n",
         "Requirement already satisfied: aiosignal>=1.1.2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain<0.3,>=0.1.16->google-cloud-aiplatform[langchain,reasoningengine]) (1.3.1)\n",
         "Requirement already satisfied: attrs>=17.3.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain<0.3,>=0.1.16->google-cloud-aiplatform[langchain,reasoningengine]) (24.2.0)\n",
         "Requirement already satisfied: frozenlist>=1.1.1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain<0.3,>=0.1.16->google-cloud-aiplatform[langchain,reasoningengine]) (1.4.1)\n",
         "Requirement already satisfied: multidict<7.0,>=4.5 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain<0.3,>=0.1.16->google-cloud-aiplatform[langchain,reasoningengine]) (6.1.0)\n",
         "Requirement already satisfied: yarl<2.0,>=1.12.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain<0.3,>=0.1.16->google-cloud-aiplatform[langchain,reasoningengine]) (1.15.1)\n",
         "Requirement already satisfied: anyio in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from httpx<0.28.0,>=0.27.0->langchain-google-vertexai<2->google-cloud-aiplatform[langchain,reasoningengine]) (4.6.0)\n",
         "Requirement already satisfied: certifi in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from httpx<0.28.0,>=0.27.0->langchain-google-vertexai<2->google-cloud-aiplatform[langchain,reasoningengine]) (2024.8.30)\n",
         "Requirement already satisfied: httpcore==1.* in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from httpx<0.28.0,>=0.27.0->langchain-google-vertexai<2->google-cloud-aiplatform[langchain,reasoningengine]) (1.0.6)\n",
         "Requirement already satisfied: idna in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from httpx<0.28.0,>=0.27.0->langchain-google-vertexai<2->google-cloud-aiplatform[langchain,reasoningengine]) (3.10)\n",
         "Requirement already satisfied: sniffio in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from httpx<0.28.0,>=0.27.0->langchain-google-vertexai<2->google-cloud-aiplatform[langchain,reasoningengine]) (1.3.1)\n",
         "Requirement already satisfied: h11<0.15,>=0.13 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from httpcore==1.*->httpx<0.28.0,>=0.27.0->langchain-google-vertexai<2->google-cloud-aiplatform[langchain,reasoningengine]) (0.14.0)\n",
         "Requirement already satisfied: jsonpointer>=1.9 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from jsonpatch<2.0,>=1.33->langchain-core<0.3->google-cloud-aiplatform[langchain,reasoningengine]) (3.0.0)\n",
         "Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from langsmith<0.2.0,>=0.1.17->langchain<0.3,>=0.1.16->google-cloud-aiplatform[langchain,reasoningengine]) (1.0.0)\n",
         "Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0dev,>=2.14.1->google-cloud-aiplatform[langchain,reasoningengine]) (0.6.1)\n",
         "Requirement already satisfied: six>=1.5 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from python-dateutil<3.0dev,>=2.7.3->google-cloud-bigquery!=3.20.0,<4.0.0dev,>=1.15.0->google-cloud-aiplatform[langchain,reasoningengine]) (1.16.0)\n",
         "Requirement already satisfied: charset-normalizer<4,>=2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-cloud-aiplatform[langchain,reasoningengine]) (3.4.0)\n",
         "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-cloud-aiplatform[langchain,reasoningengine]) (2.2.3)\n",
         "Requirement already satisfied: greenlet!=0.4.17 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from SQLAlchemy<3,>=1.4->langchain<0.3,>=0.1.16->google-cloud-aiplatform[langchain,reasoningengine]) (3.1.1)\n",
         "Requirement already satisfied: setuptools>=16.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from opentelemetry-instrumentation->openinference-instrumentation-langchain<0.2,>=0.1.19->google-cloud-aiplatform[langchain,reasoningengine]) (59.6.0)\n",
         "Requirement already satisfied: zipp>=0.5 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from importlib-metadata<=8.4.0,>=6.0->opentelemetry-api->openinference-instrumentation-langchain<0.2,>=0.1.19->google-cloud-aiplatform[langchain,reasoningengine]) (3.20.2)\n",
         "Requirement already satisfied: propcache>=0.2.0 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from yarl<2.0,>=1.12.0->aiohttp<4.0.0,>=3.8.3->langchain<0.3,>=0.1.16->google-cloud-aiplatform[langchain,reasoningengine]) (0.2.0)\n",
         "Requirement already satisfied: exceptiongroup>=1.0.2 in /home/imrenagi/projects/generative-ai/.venv/lib/python3.10/site-packages (from anyio->httpx<0.28.0,>=0.27.0->langchain-google-vertexai<2->google-cloud-aiplatform[langchain,reasoningengine]) (1.2.2)\n",
         "Using cached langchain-0.2.16-py3-none-any.whl (1.0 MB)\n",
         "Using cached langchain_core-0.2.41-py3-none-any.whl (397 kB)\n",
         "Using cached langchain_google_vertexai-1.0.10-py3-none-any.whl (86 kB)\n",
         "Using cached langchain_text_splitters-0.2.4-py3-none-any.whl (25 kB)\n",
         "Installing collected packages: langchain-core, langchain-text-splitters, langchain, langchain-google-vertexai\n",
         "  Attempting uninstall: langchain-core\n",
         "    Found existing installation: langchain-core 0.3.10\n",
         "    Uninstalling langchain-core-0.3.10:\n",
         "      Successfully uninstalled langchain-core-0.3.10\n",
         "  Attempting uninstall: langchain-text-splitters\n",
         "    Found existing installation: langchain-text-splitters 0.3.0\n",
         "    Uninstalling langchain-text-splitters-0.3.0:\n",
         "      Successfully uninstalled langchain-text-splitters-0.3.0\n",
         "  Attempting uninstall: langchain\n",
         "    Found existing installation: langchain 0.3.3\n",
         "    Uninstalling langchain-0.3.3:\n",
         "      Successfully uninstalled langchain-0.3.3\n",
         "  Attempting uninstall: langchain-google-vertexai\n",
         "    Found existing installation: langchain-google-vertexai 2.0.5\n",
         "    Uninstalling langchain-google-vertexai-2.0.5:\n",
         "      Successfully uninstalled langchain-google-vertexai-2.0.5\n",
         "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
         "langchain-community 0.3.2 requires langchain<0.4.0,>=0.3.3, but you have langchain 0.2.16 which is incompatible.\n",
         "langchain-community 0.3.2 requires langchain-core<0.4.0,>=0.3.10, but you have langchain-core 0.2.41 which is incompatible.\u001b[0m\u001b[31m\n",
         "\u001b[0mSuccessfully installed langchain-0.2.16 langchain-core-0.2.41 langchain-google-vertexai-1.0.10 langchain-text-splitters-0.2.4\n",
         "Note: you may need to restart the kernel to use updated packages.\n"
        ]
       }
      ],
      "source": [
       "%pip install -U \\\n",
       "    google-cloud-aiplatform \\\n",
       "    langchain \\\n",
       "    langchain_core \\\n",
       "    langchain_community \\\n",
       "    langchain-google-vertexai \\\n",
       "    cloudpickle==3.0.0 \\\n",
       "    pydantic==2.7.4 \\\n",
       "    langchain_google_community \\\n",
       "    google-cloud-discoveryengine \\\n",
       "    google-api-python-client \\\n",
       "    google-auth \\\n",
       "    nest-asyncio \\\n",
       "    psycopg2 \\\n",
       "    psycopg2-binary\n",
       "\n",
       "%pip install \\\n",
       "    asyncio==3.4.3 asyncpg==0.27.0 cloud-sql-python-connector[\"asyncpg\"]==1.2.3 \\\n",
       "    numpy pandas \\\n",
       "    pgvector \n",
       "\n",
       "%pip install -U google-cloud-aiplatform[langchain,reasoningengine] "
      ]
     },
     {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
       "if facing issue with pycopg2\n",
       "\n",
       "```\n",
       "sudo apt-get update\n",
       "sudo apt-get install python3-dev libpq-dev\n",
       "```"
      ]
     },
     {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {},
      "outputs": [
       {
        "data": {
         "text/plain": [
          "{'status': 'ok', 'restart': True}"
         ]
        },
        "execution_count": 2,
        "metadata": {},
        "output_type": "execute_result"
       },
       {
        "ename": "",
        "evalue": "",
        "output_type": "error",
        "traceback": [
         "\u001b[1;31mThe Kernel crashed while executing code in the current cell or a previous cell. \n",
         "\u001b[1;31mPlease review the code in the cell(s) to identify a possible cause of the failure. \n",
         "\u001b[1;31mClick <a href='https://aka.ms/vscodeJupyterKernelCrash'>here</a> for more info. \n",
         "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
        ]
       }
      ],
      "source": [
       "import IPython\n",
       "\n",
       "app = IPython.Application.instance()\n",
       "app.kernel.do_shutdown(True)"
      ]
     },
     {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {},
      "outputs": [],
      "source": [
       "project_id = \"imrenagi-gemini-experiment\" #change this to your project id\n",
       "region = \"us-central1\" "
      ]
     },
     {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {},
      "outputs": [
       {
        "data": {
         "text/plain": [
          "'896489987664'"
         ]
        },
        "execution_count": 2,
        "metadata": {},
        "output_type": "execute_result"
       }
      ],
      "source": [
       "from googleapiclient import discovery\n",
       "service = discovery.build(\"cloudresourcemanager\", \"v1\")\n",
       "request = service.projects().get(projectId=project_id)\n",
       "response = request.execute()\n",
       "project_number = response[\"projectNumber\"]\n",
       "project_number"
      ]
     },
     {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
       "!gcloud services enable aiplatform.googleapis.com\n",
       "!gcloud services enable run.googleapis.com cloudbuild.googleapis.com\n",
       "\n",
       "!gcloud projects add-iam-policy-binding {project_id} \\\n",
       "    --member=serviceAccount:{project_number}-compute@developer.gserviceaccount.com \\\n",
       "    --role=roles/cloudbuild.builds.builder"
      ]
     },
     {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
       "!echo ${PWD}\n",
       "!./api/deploy.sh"
      ]
     },
     {
      "cell_type": "code",
      "execution_count": 8,
      "metadata": {},
      "outputs": [
       {
        "name": "stdout",
        "output_type": "stream",
        "text": [
         "https://courses-api-uzttxm4diq-uc.a.run.app\n"
        ]
       }
      ],
      "source": [
       "!gcloud run services describe courses-api --region=us-central1 --format='value(status.url)'"
      ]
     },
     {
      "cell_type": "code",
      "execution_count": 9,
      "metadata": {},
      "outputs": [
       {
        "name": "stdout",
        "output_type": "stream",
        "text": [
         "Creating gs://courses-imrenagicom-agent/...\n",
         "\u001b[1;31mERROR:\u001b[0m (gcloud.storage.buckets.create) HTTPError 409: Your previous request to create the named bucket succeeded and you already own it.\n"
        ]
       }
      ],
      "source": [
       "# change this with globaly unique name. you may add your name to make it unique. this bucket will be used later for storing the model\n",
       "staging_bucket_name = \"courses-imrenagicom-agent\"\n",
       "\n",
       "!gcloud storage buckets create gs://{staging_bucket_name} --project={project_id} --location={region} --uniform-bucket-level-access"
      ]
     }
    ],
    "metadata": {
     "kernelspec": {
      "display_name": ".venv",
      "language": "python",
      "name": "python3"
     },
     "language_info": {
      "codemirror_mode": {
       "name": "ipython",
       "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.11.10"
     }
    },
    "nbformat": 4,
    "nbformat_minor": 2
   }
   